name: Pull Request for Docs Release
on:
  push:
    branches:
      - 'docs-release-*'
jobs:
  auto-create-pull-request:
    name: Auto-Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        run: hub pull-request -m "Release docs for ${GITHUB_REF:24}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
